openapi: 3.0.1
info:
  title: HelloWorld
  description: API Definition of HelloWorld
  version: 1.0.0
servers:
- url: "{server}:{port}/HelloWorld"
  variables:
    server:
      default: http://localhost
    port:
      default: "8290"
paths:
  /{paths}:
    get:
      responses:
        default:
          description: Default response
